Druid Hello World window
This must be compiled using master branch, hence Cargo.toml has the
druid dependency as:
  druid = { git = "https://github.com/linebender/druid.git" }

If you used `druid = "0.7.0" you get and E0277 error about the
parameter to WindowDesc::new not implementing FnOnce:

     Compiling expr-druid-1 v0.1.0 (/home/wink/prgs/rust/myrepos/expr-druid-1)
  error[E0277]: expected a `FnOnce<()>` closure, found `impl druid::Widget<()>`
     --> src/main.rs:9:46
      |
  9   |     AppLauncher::with_window(WindowDesc::new(build_ui())).launch(())?;
      |                                              ^^^^^^^^^^ expected an `FnOnce<()>` closure, found `impl druid::Widget<()>`
      |
     ::: /home/wink/.cargo/registry/src/github.com-1ecc6299db9ec823/druid-0.7.0/src/app.rs:347:28
      |
  347 |         F: FnOnce() -> W + 'static,
      |                            ------- required by this bound in `WindowDesc::<T>::new`
      |
      = help: the trait `FnOnce<()>` is not implemented for `impl druid::Widget<()>`
      = note: wrap the `impl druid::Widget<()>` in a closure with no arguments: `|| { /* code */ }`

  For more information about this error, try `rustc --explain E0277`.
  error: could not compile `expr-druid-1` due to previous error